name: Update to latest version of RangeMessage.xml
on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Curl RangeMessage.xml.
      uses: wei/curl@v1.1.1
      with:
        args: https://www.isbn-international.org/export_rangemessage.xml
    - name: Send PR.
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: "Update to latest RangeMessage.xml"
